import type { TaskIntent, Subtask } from "./intent-parser"

export interface DecompositionRule {
  pattern: RegExp | string
  keywords: string[]
  template: (context: string) => Subtask[]
}

export class Planner {
  private rules: DecompositionRule[] = [
    {
      pattern: /add|create|build|implement/i,
      keywords: ["feature", "component", "module", "page", "endpoint", "api"],
      template: (goal: string) => [
        { id: "plan-types", description: "Define TypeScript interfaces and types needed", dependsOn: [], verificationCriteria: ["No type errors"] },
        { id: "plan-impl", description: `Implement: ${goal}`, dependsOn: ["plan-types"], verificationCriteria: ["Tests pass"] },
        { id: "plan-tests", description: "Write comprehensive unit tests", dependsOn: ["plan-impl"], verificationCriteria: ["All tests pass"] },
      ],
    },
    {
      pattern: /fix|bug|repair|resolve|patch/i,
      keywords: ["bug", "issue", "error", "crash", "broken"],
      template: (goal: string) => [
        { id: "fix-repro", description: "Reproduce the bug and add a failing test", dependsOn: [], verificationCriteria: ["Test reproduces the error"] },
        { id: "fix-root", description: `Identify root cause and apply fix: ${goal}`, dependsOn: ["fix-repro"], verificationCriteria: ["Failing test now passes"] },
        { id: "fix-regression", description: "Run full test suite to check for regressions", dependsOn: ["fix-root"], verificationCriteria: ["All tests pass"] },
      ],
    },
    {
      pattern: /refactor|clean|restructure|extract/i,
      keywords: ["refactor", "cleanup", "extract", "move", "rename"],
      template: (goal: string) => [
        { id: "refactor-audit", description: "Audit current implementation and document dependencies", dependsOn: [], verificationCriteria: ["Dependency map created"] },
        { id: "refactor-extract", description: `Extract and restructure: ${goal}`, dependsOn: ["refactor-audit"], verificationCriteria: ["Tests still pass"] },
        { id: "refactor-cleanup", description: "Remove old code and update references", dependsOn: ["refactor-extract"], verificationCriteria: ["No dead code", "Tests pass"] },
      ],
    },
    {
      pattern: /test|spec|verify/i,
      keywords: ["test", "spec", "coverage", "verify"],
      template: (goal: string) => [
        { id: "test-audit", description: "Identify untested code paths and edge cases", dependsOn: [], verificationCriteria: ["Coverage gaps documented"] },
        { id: "test-write", description: `Write tests: ${goal}`, dependsOn: ["test-audit"], verificationCriteria: ["New tests pass"] },
        { id: "test-verify", description: "Run full suite and verify coverage improved", dependsOn: ["test-write"], verificationCriteria: ["Coverage increased"] },
      ],
    },
  ]

  decompose(goal: string, relevantFiles: string[]): { intent: TaskIntent; autoGenerated: boolean } {
    const intent: TaskIntent = {
      goal,
      constraints: [],
      context: { relevantFiles, dependencies: [] },
      subtasks: [],
    }

    for (const rule of this.rules) {
      const patternMatch = typeof rule.pattern === "string"
        ? goal.toLowerCase().includes(rule.pattern.toLowerCase())
        : rule.pattern.test(goal)

      const keywordMatch = rule.keywords.some(k => goal.toLowerCase().includes(k.toLowerCase()))

      if (patternMatch && keywordMatch) {
        intent.subtasks = rule.template(goal)
        return { intent, autoGenerated: true }
      }
    }

    return { intent, autoGenerated: false }
  }

  suggestSubtask(id: string, description: string, dependsOn: string[] = []): Subtask {
    return { id, description, dependsOn, verificationCriteria: [] }
  }
}
