import type { TaskIntent, Subtask } from "./intent-parser.js"
import type { LLMEngine } from "./llm.js"
import { DependencyGraph } from "./formal-model.js"
import type { PlannerCritic, CriticResult, CriticScore } from "./planner-critic.js"
import { createDefaultRules, createMacroTemplates } from "./planner-data.js"
import { computePhaseOrder, computeSubgoalScore } from "./planner-utils.js"

export interface MacroPhase {
  id: string
  name: string
  description: string
  goal: string
  dependsOn: string[]
  /** Expected outcome of this phase */
  outcome: string
  /** Schema of expected outputs (for context passing to dependent phases) */
  outputSchema?: Record<string, string>
  /** Schema of expected inputs (from parent phases) */
  inputSchema?: Record<string, string>
}

/**
 * Context mapping between two phases.
 * Describes how output fields from one phase map to input fields of another.
 */
export interface PhaseContextMapping {
  /** Source phase ID */
  fromPhaseId: string
  /** Target phase ID */
  toPhaseId: string
  /** Field mappings: outputField → inputField */
  mappings: Record<string, string>
}

/** Error context for phase retry */
export interface PhaseErrorContext {
  phaseId: string
  error: string
  failedStepIds: string[]
}

export interface MicroStep {
  id: string
  phaseId: string
  description: string
  dependsOn: string[]
  verificationCriteria: string[]
}

export interface HierarchicalPlan {
  goal: string
  phases: MacroPhase[]
  /** Detailed steps per phase */
  micro: Map<string, MicroStep[]>
  /** Topological order of all phases */
  phaseOrder: string[]
}

export interface MacroTemplate {
  pattern: RegExp | string
  keywords: string[]
  /** Generate phases for a goal */
  phases: (goal: string) => MacroPhase[]
  /** Expand a phase into micro-steps */
  expand: (phase: MacroPhase, goal: string) => MicroStep[]
  domain?: string
}

export interface DecompositionRule {
  pattern: RegExp | string
  keywords: string[]
  template: (context: string) => Subtask[]
  domain?: string
}

export class Planner {
  private rules = createDefaultRules()

  decompose(goal: string, relevantFiles: string[], activeDomain?: string): { intent: TaskIntent; autoGenerated: boolean } {
    const intent: TaskIntent = {
      goal,
      constraints: [],
      context: { relevantFiles, dependencies: [] },
      subtasks: [],
    }

    let bestScore = 0
    let bestRule: DecompositionRule | null = null
    for (const rule of this.rules) {
      const patternMatch = typeof rule.pattern === "string"
        ? goal.toLowerCase().includes(rule.pattern.toLowerCase())
        : rule.pattern.test(goal)

      const keywordMatch = rule.keywords.some(k => goal.toLowerCase().includes(k.toLowerCase()))
      if (!patternMatch && !keywordMatch) continue
      if (rule.domain && rule.domain !== activeDomain) continue

      // Score: specific patterns + domain match + keyword density
      let score = patternMatch ? 2 : 0
      score += keywordMatch ? 1 : 0
      const kwCount = rule.keywords.filter(k => goal.toLowerCase().includes(k.toLowerCase())).length
      score += kwCount * 0.5
      if (rule.domain) score += 1

      if (score > bestScore) {
        bestScore = score
        bestRule = rule
      }
    }

    if (bestRule) {
      intent.subtasks = bestRule.template(goal)
      this.breakCycles(intent.subtasks)
      return { intent, autoGenerated: true }
    }

    // Fallback: create a generic step so the task isn't treated as instantly complete
    intent.subtasks = [{
      id: "generic-execute",
      description: goal,
      dependsOn: [],
      verificationCriteria: [],
    }]
    return { intent, autoGenerated: true }
  }

  private breakCycles(subtasks: Subtask[]): void {
    const graph = new DependencyGraph()
    for (const step of subtasks) {
      for (const dep of step.dependsOn) {
        graph.addEdge(dep, step.id)
      }
    }
    const vertices = subtasks.map(s => s.id)
    const cycle = graph.detectCycle(vertices)
    if (cycle.hasCycle) {
      const cycleSet = new Set(cycle.cyclePath ?? [])
      for (const step of subtasks) {
        if (!cycleSet.has(step.id)) continue
        step.dependsOn = step.dependsOn.filter(d => !cycleSet.has(d))
      }
      const fixedGraph = new DependencyGraph()
      for (const step of subtasks) {
        for (const dep of step.dependsOn) {
          fixedGraph.addEdge(dep, step.id)
        }
      }
      const fixedCycle = fixedGraph.detectCycle(vertices)
      if (fixedCycle.hasCycle) {
        for (const step of subtasks) {
          step.dependsOn = []
        }
      }
    }
  }

  registerRule(rule: DecompositionRule): void {
    this.rules.push(rule)
  }

  getRules(): DecompositionRule[] {
    return [...this.rules]
  }

  private critic: PlannerCritic | null = null

  /** Set PlannerCritic instance for self-reflection planning */
  setCritic(critic: PlannerCritic): void {
    this.critic = critic
  }

  /** Check if critic is available */
  hasCritic(): boolean {
    return this.critic !== null
  }

  async decomposeWithLLM(llm: LLMEngine, goal: string, codebaseSummary: string): Promise<TaskIntent> {
    const llmPlan = await llm.generatePlan(goal, [], codebaseSummary)
    const subtasks = Array.isArray(llmPlan.steps)
      ? llmPlan.steps.map((s, i) => ({
          id: s.id || `step-${i + 1}`,
          description: s.description,
          dependsOn: s.dependsOn ?? [],
          verificationCriteria: [],
        }))
      : []
    const intent: TaskIntent = {
      goal,
      constraints: [],
      context: { relevantFiles: [], dependencies: [] },
      subtasks,
    }
    return intent
  }

  /**
   * Decompose using PlannerCritic self-reflection loop.
   * Generates multiple candidates, evaluates, refines.
   */
  async decomposeWithCritic(goal: string, codebaseSummary: string): Promise<CriticResult> {
    if (!this.critic) {
      // Fallback: return empty CriticResult
      return {
        plan: { goal, constraints: [], context: { relevantFiles: [], dependencies: [] }, subtasks: [] },
        candidates: [],
        scores: [],
        bestScore: 0,
        iterations: 0,
        accepted: false,
      }
    }
    return this.critic.refinePlan(goal, codebaseSummary)
  }

  suggestSubtask(id: string, description: string, dependsOn: string[] = []): Subtask {
    return { id, description, dependsOn, verificationCriteria: [] }
  }

  private macroTemplates = createMacroTemplates()

  /**
   * Select the best matching macro template for a goal.
   * Returns null if no template matches with sufficient score.
   */
  private selectMacroTemplate(goal: string, activeDomain?: string): MacroTemplate | null {
    let bestScore = 0
    let bestTemplate: MacroTemplate | null = null
    for (const tmpl of this.macroTemplates) {
      const patternMatch = typeof tmpl.pattern === "string"
        ? goal.toLowerCase().includes(tmpl.pattern.toLowerCase())
        : tmpl.pattern.test(goal)
      const keywordMatch = tmpl.keywords.some(k => goal.toLowerCase().includes(k.toLowerCase()))
      if (!patternMatch && !keywordMatch) continue
      if (tmpl.domain && tmpl.domain !== activeDomain) continue
      const score = (patternMatch ? 2 : 0) + (keywordMatch ? 1 : 0)
      if (score > bestScore) {
        bestScore = score
        bestTemplate = tmpl
      }
    }
    return bestTemplate
  }

  /**
   * Decompose a goal into macro-level phases.
   * Returns a list of ordered phases with dependencies.
   * Falls back to a default 3-phase plan if no template matches.
   */
  decomposeMacro(goal: string, activeDomain?: string): HierarchicalPlan {
    const template = this.selectMacroTemplate(goal, activeDomain)
    let phases: MacroPhase[]
    if (template) {
      phases = template.phases(goal)
    } else {
      phases = [
        { id: "phase-plan", name: "Plan", description: `Plan: ${goal}`, goal, dependsOn: [], outcome: "Plan ready" },
        { id: "phase-execute", name: "Execute", description: `Execute: ${goal}`, goal, dependsOn: ["phase-plan"], outcome: "Execution complete" },
        { id: "phase-verify", name: "Verify", description: `Verify: ${goal}`, goal, dependsOn: ["phase-execute"], outcome: "Verified" },
      ]
    }

    const phaseOrder = computePhaseOrder(phases)

    const plan: HierarchicalPlan = {
      goal,
      phases,
      micro: new Map(),
      phaseOrder,
    }

    this.expandAll(plan, template)
    return plan
  }

  /**
   * Expand a specific phase into detailed micro-steps.
   * Uses the template's expand function if available, otherwise generic.
   */
  expandPhase(phase: MacroPhase, goal: string, template?: MacroTemplate | null): MicroStep[] {
    if (template) {
      return template.expand(phase, goal)
    }
    return [
      { id: `${phase.id}-1`, phaseId: phase.id, description: `Prepare for phase: ${phase.name}`, dependsOn: [], verificationCriteria: ["Ready"] },
      { id: `${phase.id}-2`, phaseId: phase.id, description: `Complete phase: ${phase.name}`, dependsOn: [`${phase.id}-1`], verificationCriteria: ["Complete"] },
    ]
  }

  /**
   * Expand all phases in a hierarchical plan into micro-steps,
   * producing the flat step list for execution.
   */
  expandAll(plan: HierarchicalPlan, template?: MacroTemplate | null): void {
    for (const phase of plan.phases) {
      const steps = this.expandPhase(phase, plan.goal, template)
      plan.micro.set(phase.id, steps)
    }
  }

  /**
   * Convert a hierarchical plan into a flat list of Subtasks for execution.
   * Each micro-step becomes a Subtask with dependencies linked intra- and inter-phase.
   */
  flattenHierarchical(plan: HierarchicalPlan): Subtask[] {
    const subtasks: Subtask[] = []
    const processed = new Set<string>()

    for (const phaseId of plan.phaseOrder) {
      const steps = plan.micro.get(phaseId) ?? []
      const phase = plan.phases.find(p => p.id === phaseId)
      const depPhaseId = phase?.dependsOn?.[0]
      const depSteps = depPhaseId ? plan.micro.get(depPhaseId) ?? [] : []
      const lastPrevStep = depSteps.length > 0
        ? depSteps[depSteps.length - 1].id
        : null

      for (const step of steps) {
        if (processed.has(step.id)) continue
        processed.add(step.id)

        const deps = step.dependsOn.filter(d => processed.has(d))
        if (deps.length === 0 && lastPrevStep && subtasks.length > 0) {
          deps.push(lastPrevStep)
        }

        subtasks.push({
          id: step.id,
          description: step.description,
          dependsOn: deps,
          verificationCriteria: step.verificationCriteria,
        })
      }
    }

    return subtasks
  }

  // ── Context Passing (Gap #1: output → input antar phase) ──────

  /**
   * Compute context mappings between sequential phases.
   * For each dependency relationship (phase A depends on phase B),
   * maps declared outputSchema fields of B to inputSchema fields of A.
   */
  applyContextPassing(plan: HierarchicalPlan): PhaseContextMapping[] {
    const mappings: PhaseContextMapping[] = []
    const phaseMap = new Map(plan.phases.map(p => [p.id, p]))

    for (const phase of plan.phases) {
      if (!phase.inputSchema || Object.keys(phase.inputSchema).length === 0) continue

      for (const depId of phase.dependsOn) {
        const depPhase = phaseMap.get(depId)
        if (!depPhase || !depPhase.outputSchema) continue

        const fieldMappings: Record<string, string> = {}
        const usedOutputs = new Set<string>()

        // First pass: match by exact name
        for (const [inField] of Object.entries(phase.inputSchema)) {
          if (depPhase.outputSchema[inField]) {
            fieldMappings[inField] = inField
            usedOutputs.add(inField)
          }
        }

        // Second pass: match remaining by type
        const remainingInput = Object.entries(phase.inputSchema).filter(([k]) => !fieldMappings[k])
        const remainingOutput = Object.entries(depPhase.outputSchema).filter(([k]) => !usedOutputs.has(k))
        for (const [inField, inType] of remainingInput) {
          for (const [outField, outType] of remainingOutput) {
            if (inType === outType && !usedOutputs.has(outField)) {
              fieldMappings[outField] = inField
              usedOutputs.add(outField)
              break
            }
          }
        }

        if (Object.keys(fieldMappings).length > 0) {
          mappings.push({
            fromPhaseId: depId,
            toPhaseId: phase.id,
            mappings: fieldMappings,
          })
        }
      }
    }

    return mappings
  }

  // ── Per-subgoal Error Recovery (Gap #2: retryPhase) ──────────

  /**
   * Retry a failed phase by re-expanding it with error context.
   * Returns a new set of micro-steps with adjusted descriptions
   * that incorporate the failure information.
   *
   * @param plan — the hierarchical plan
   * @param failedPhaseId — ID of the phase that failed
   * @param errorContext — what went wrong (error message + failed step IDs)
   * @param template — optional macro template for re-expansion
   */
  retryPhase(
    plan: HierarchicalPlan,
    failedPhaseId: string,
    errorContext: PhaseErrorContext,
    template?: MacroTemplate | null,
  ): MicroStep[] {
    const phase = plan.phases.find(p => p.id === failedPhaseId)
    if (!phase) return []

    // Include error context in the goal for re-expansion
    const adjustedGoal = `${plan.goal} (retry after: ${errorContext.error})`
    const newSteps = this.expandPhase(phase, adjustedGoal, template)

    // Mark the new steps as retry steps
    const retrySteps: MicroStep[] = newSteps.map((step, i) => ({
      ...step,
      id: `${step.id}-retry-${i}`,
      description: `${step.description} [retry #${i + 1}: avoid "${errorContext.error}"]`,
      verificationCriteria: [
        ...step.verificationCriteria,
        `Fixed error: ${errorContext.error}`,
      ],
    }))

    // Replace phase micro-steps in plan
    plan.micro.set(failedPhaseId, retrySteps)

    return retrySteps
  }

  // ── Per-subgoal Critic Integration (Gap #3) ──────────────────

  /**
   * Critically evaluate a single phase's micro-steps.
   * Returns issues and suggestions for this specific sub-goal.
   *
   * @param phase — the macro phase to evaluate
   * @param microSteps — the micro-steps generated for this phase
   * @param critic — optional PlannerCritic instance for LLM-based evaluation
   */
  criticizeSubgoal(
    phase: MacroPhase,
    microSteps: MicroStep[],
    _critic?: PlannerCritic,
  ): CriticScore {
    const issues: string[] = []
    const suggestions: string[] = []

    // Structural validation (always available)
    if (microSteps.length === 0) {
      issues.push(`Phase "${phase.name}" has no micro-steps`)
      suggestions.push("Expand the phase with at least one actionable step")
    }
    if (microSteps.length > 5) {
      issues.push(`Phase "${phase.name}" has ${microSteps.length} steps (max 5 recommended)`)
      suggestions.push("Consider splitting this phase into smaller sub-phases")
    }

    // Check step descriptions are concrete
    const vagueWords = ["stuff", "things", "etc", "misc", "whatever", "todo"]
    for (const step of microSteps) {
      for (const word of vagueWords) {
        if (step.description.toLowerCase().includes(word)) {
          issues.push(`Step "${step.id}" contains vague word "${word}": "${step.description}"`)
          suggestions.push(`Replace vague descriptions with concrete actions`)
          break
        }
      }
    }

    // Check dependency completeness
    const stepIds = new Set(microSteps.map(s => s.id))
    for (const step of microSteps) {
      for (const dep of step.dependsOn) {
        if (!stepIds.has(dep)) {
          issues.push(`Step "${step.id}" depends on unknown step "${dep}"`)
          suggestions.push("Fix dependency references to valid step IDs")
        }
      }
    }

    // Check verification criteria
    const stepsWithoutCriteria = microSteps.filter(s => !s.verificationCriteria || s.verificationCriteria.length === 0)
    if (stepsWithoutCriteria.length > 0) {
      issues.push(`${stepsWithoutCriteria.length} step(s) without verification criteria`)
      suggestions.push("Add at least one verification criterion per step")
    }

    const score = computeSubgoalScore(issues, microSteps.length)

    return { overall: score, issues, suggestions }
  }
}
