import { tool } from "@opencode-ai/plugin"
import type { ToolSpec } from "./types.js"
import type { ToolContext } from "./tool-context.js"
import type { TaskIntent } from "../core/intent-parser.js"
import { codeIntentAnalyzer } from "../core/code-intent-analyzer.js"
import type { SimulatedStep } from "../core/simulation-engine.js"

export function makePlanTool(ctx: ToolContext): ToolSpec {
  const {
    sessionStore, domainRegistry, worktree, projectId, config,
    log, projectContext, TOOL_REGISTRY, currentInjectDomain,
    planner, plannerCritic, executor, intentParser, agentLoop,
    verifier, errorAnalyzer, errorRecovery, alignmentGate,
    economicModel, confidenceScorer, confidenceStore, techDebtScorer,
    constraintManifold, navigator, toolRouter, routerAgent,
    skillStore, skillCurator, episodicStore, memoryOrchestrator,
    secondBrain, rag: multiIndexRAG, coordinator, orchestrator,
    roleRegistry, agentRuntime, debateLoop, dashboard, traceLogger,
    liveEvaluator, patternDiscovery, toolUsageTracker, workflowEngine,
    llmEngine, modelRegistry, hallucinationGuard, checkpoints,
    stateStore, budgetTracker, eventBus, parallelExec,
    dependencyTracker: depTracker, contextCompressor, git,
    selfEvolver, continuousEvolution, metaReasoner,
    mcpServer, mcpClient, protocolAdapter, dynamicToolRegistry,
    worldModel, simulationEngine, dataCleaner, configLoader,
    logErrorToFile, detectSubAgentRole, buildSubAgentInjection, ctxDir,
  } = ctx
  return {
      description: "Create a structured execution plan. Can auto-decompose feature requests using built-in templates (create/implement, fix/bug, refactor, test, deploy, migrate, doc, perf). Use `llmDecompose: true` for AI-powered decomposition. Call this FIRST for any multi-step task.",
      args: {
        goal: tool.schema.string().describe("The overall goal of the task"),
        constraints: tool.schema.array(tool.schema.string()).optional().describe("Constraints or requirements"),
        relevantFiles: tool.schema.array(tool.schema.string()).optional().describe("Files relevant to this task"),
        autoDecompose: tool.schema.boolean().optional().describe("Auto-decompose the goal into subtasks (default: true). Uses LLM first, falls back to built-in templates."),
        llmDecompose: tool.schema.boolean().optional().describe("Use LLM for smarter task decomposition (default: true, falls back to templates if LLM unavailable)"),
        criticRefine: tool.schema.boolean().optional().describe("Use PlannerCritic self-reflection loop: generate multiple candidates, evaluate, refine (default: false). Only effective when llmDecompose is true."),
        subtasks: tool.schema.array(tool.schema.object({
          id: tool.schema.string().describe("Unique identifier for this subtask"),
          description: tool.schema.string().describe("What this subtask should accomplish"),
          dependsOn: tool.schema.array(tool.schema.string()).optional().describe("IDs of subtasks that must be completed first"),
          verificationCriteria: tool.schema.array(tool.schema.string()).optional().describe("How to verify this subtask succeeded"),
        })).optional().describe("Manual subtask list. If omitted and autoDecompose is enabled, the planner will auto-generate steps."),
      },
      async execute(args, context) {
        let subtasks = args.subtasks ?? []

        if (subtasks.length === 0 && args.autoDecompose !== false) {
          // Episodic Plan Reuse: check for similar past successful plans first
          const reuseEpisodes = episodicStore.searchForReuse(args.goal)
          if (reuseEpisodes.length > 0) {
            const best = reuseEpisodes[0]
            episodicStore.incrementUsage(best.id)
            const adapted = episodicStore.adaptPlan(best, args.goal)
            if (adapted && adapted.length > 0) {
              subtasks = adapted.map((desc, i) => ({
                id: `reuse-${i + 1}`,
                description: desc,
                dependsOn: i > 0 ? [`reuse-${i}`] : [],
                verificationCriteria: [],
              }))
            }
          }

          // Fast path: template-based decomposition (no LLM) — only if reuse didn't produce steps
          if (subtasks.length === 0) {
          const activeDomain = domainRegistry.getCurrentDomain() ?? undefined
          const decomposition = planner.decompose(args.goal, args.relevantFiles ?? [], activeDomain)
          if (decomposition.autoGenerated) {
            subtasks = decomposition.intent.subtasks
          }

          // Optional: LLM decomposition (only if explicitly requested)
          if (subtasks.length === 0 && args.llmDecompose === true) {
            const scanDir = context.directory || context.worktree || worktree
            try {
              await navigator.scan(scanDir)
            } catch (e) { log.warn("Silent catch: non-fatal", { error: String(e) }) }
            const codebaseSummary = navigator.getSummary()
            try {
              const llmIntent = await planner.decomposeWithLLM(llmEngine, args.goal, codebaseSummary)
              subtasks = llmIntent.subtasks
            } catch (e) { log.warn("Silent catch: Fall through to template-based", { error: String(e) }) }
          }
        }
        }

        // PlannerCritic self-reflection refinement (optional)
        if (args.criticRefine === true && subtasks.length > 0 && planner.hasCritic()) {
          try {
            const scanDir = context.directory || context.worktree || worktree
            let codebaseSummary = ""
            try { await navigator.scan(scanDir); codebaseSummary = navigator.getSummary() } catch (e) { log.warn("Silent catch: non-fatal", { error: String(e) }) }
            const criticResult = await planner.decomposeWithCritic(args.goal, codebaseSummary)
            if (criticResult.accepted && criticResult.plan.subtasks.length > 0) {
              subtasks = criticResult.plan.subtasks.map(s => ({
                id: s.id,
                description: s.description,
                dependsOn: s.dependsOn ?? [],
                verificationCriteria: s.verificationCriteria ?? [],
              }))
            }
          } catch (e) { log.warn("Silent catch: non-fatal — fall through to existing plan", { error: String(e) }) }
        }

        const intent: TaskIntent = {
          goal: args.goal,
          constraints: args.constraints ?? [],
          context: {
            relevantFiles: args.relevantFiles ?? [],
            dependencies: [],
          },
          subtasks: subtasks.map((s: { id: string; description: string; dependsOn?: string[]; verificationCriteria?: string[] }) => ({
            id: s.id,
            description: s.description,
            dependsOn: s.dependsOn ?? [],
            verificationCriteria: s.verificationCriteria ?? [],
          })),
        }

        const plan = intentParser.createPlan(intent)
        const errors = intentParser.validatePlan(plan)

        executor.initExecution(context.sessionID, plan)
        const planSession = sessionStore.getOrCreate(context.sessionID)
        planSession.plan = plan
        planSession.artifacts.set("workflow:planned", String(Date.now()))

        // Wire up dependency tracking from plan — step-level
        for (const step of subtasks) {
          for (const dep of (step.dependsOn ?? [])) {
            depTracker.addDependency(step.id, dep, "imports")
          }
        }

        // Wire file-level dependencies from navigator scan
        if (args.relevantFiles && args.relevantFiles.length > 0) {
          for (const file of args.relevantFiles) {
            depTracker.addDependency(`file:${file}`, `goal:${args.goal.slice(0, 40)}`, "type-ref")
          }
        }

        // Gap #3: Intent Inference via Program Analysis — ground the plan with function-level intent
        let codeIntentMap = null
        const projectDir = ctxDir(context)
        try {
          codeIntentMap = await codeIntentAnalyzer.analyze(args.goal, projectDir)
          if (codeIntentMap && codeIntentMap.files.length > 0) {
            sessionStore.getOrCreate(context.sessionID).codeIntentMap = codeIntentMap
            // Inject relevant files from intent analysis if none provided
            if (!args.relevantFiles || args.relevantFiles.length === 0) {
              plan.intent.context.relevantFiles = codeIntentMap.files.map(f => f.relativePath)
            }
          }
        } catch (e) { log.warn("Silent catch: Non-fatal — plan works without intent analysis", { error: String(e) }) }

        traceLogger.log({
          step: "plan",
          input: args.goal,
          output: JSON.stringify(plan),
          toolUsed: "agentic_plan",
          success: errors.length === 0,
          durationMs: 0,
          metadata: { errors, complexity: plan.complexity, autoDecomposed: (!args.subtasks || args.subtasks.length === 0) && subtasks.length > 0, llmDecomposed: !!args.llmDecompose },
        })

        // Emit plan.created event for Second Brain + observability
        eventBus.emit({
          type: "plan.created",
          payload: {
            sessionID: context.sessionID,
            planId: plan.intent.subtasks[0]?.id ?? `plan-${Date.now()}`,
            goal: plan.intent.goal,
            subtaskCount: plan.intent.subtasks.length,
            domain: domainRegistry.getCurrentDomain() ?? "generic",
          },
        })

        if (errors.length > 0) {
          return {
            output: `## Plan Created (with warnings)\n\n${errors.map(e => `⚠️  ${e}`).join("\n")}\n\n<details>\n<summary>Plan JSON</summary>\n\n\`\`\`json\n${JSON.stringify(plan, null, 2)}\n\`\`\`\n</details>`,
            metadata: { hasErrors: true, plan },
          }
        }

        const stepList = plan.intent.subtasks.map((s, i) =>
          `${i + 1}. **${s.id}** — ${s.description}${s.dependsOn.length ? ` (requires: ${s.dependsOn.join(", ")})` : ""}`
        ).join("\n")

        const autoTag = (!args.subtasks || args.subtasks.length === 0) && subtasks.length > 0 ? " (auto-decomposed)" : ""

        let planOutput = `## Plan Created${autoTag}\n\n**Goal:** ${plan.intent.goal}\n**Complexity:** ${plan.complexity}\n**Steps:** ${plan.estimatedSteps}\n\n### Steps\n${stepList}\n\nStart with \`agentic_execute\` for the first ready step.`

        const suggestedPipelineId = orchestrator.getSuggestedPipeline(args.goal)
        const suggestedPipelineObj = orchestrator.getPipeline(suggestedPipelineId)
        if (suggestedPipelineObj && suggestedPipelineObj.stages.length > 0) {
          const stageList = suggestedPipelineObj.stages.map(s => `\`${s.role}\``).join(" → ")
          planOutput += `\n\n### 💡 Suggested Pipeline\nThis goal matches the **${suggestedPipelineObj.name}** pipeline (${stageList}). Run \`agentic_pipeline action="run" pipelineId="${suggestedPipelineId}"\` to delegate to specialized agents.`
        }

        if (codeIntentMap && codeIntentMap.files.length > 0) {
          const totalFuncs = codeIntentMap.files.reduce((s, f) => s + f.functions.length, 0)
          planOutput += `\n\n### 🔍 Code Intent Analysis\n**Files analyzed:** ${codeIntentMap.files.length}  \n**Functions extracted:** ${totalFuncs}  \n**Language:** ${codeIntentMap.primaryLanguage ?? "unknown"}\n\n`
          const topFiles = codeIntentMap.files.slice(0, 3)
          for (const file of topFiles) {
            const intentTags = file.functions.slice(0, 4).map(fn => `\`${fn.functionName}\``).join(", ")
            planOutput += `- **${file.relativePath}** (${file.complexity}) — ${file.summary}`
            if (intentTags) planOutput += ` → ${intentTags}`
            planOutput += "\n"
          }
          if (codeIntentMap.files.length > 3) {
            planOutput += `  ... and ${codeIntentMap.files.length - 3} more files\n`
          }
          planOutput += `\n*Intent analysis provides program-aware grounding for implementation. Use this context with \`agentic_execute\` for better code generation.*`
        }

        // Simulation dry-run (Comparison 20: Internal Simulation)
        if (plan.intent.subtasks.length > 0) {
          try {
            const simulatedSteps: SimulatedStep[] = plan.intent.subtasks.map(s => ({
              stepId: s.id,
              description: s.description,
              complexity: Math.min(10, Math.max(1, Math.ceil(s.description.length / 50))),
              predictedSuccess: 0.7,
              estimatedTokens: 2000,
              dependsOn: s.dependsOn ?? [],
            }))
            const simResult = simulationEngine.simulate({
              planId: `plan_${Date.now()}`,
              steps: simulatedSteps,
              goal: args.goal,
            })
            if (simResult.warnings.length > 0 || !simResult.recommended) {
              planOutput += `\n\n### 🎯 Simulation Preview\n`
              planOutput += `**Score:** ${(simResult.score * 100).toFixed(0)}% | **Recommended:** ${simResult.recommended ? '✅ Yes' : '❌ No'}\n`
              planOutput += `**Overall success rate:** ${(simResult.overallSuccessRate * 100).toFixed(0)}%\n`
              if (simResult.warnings.length > 0) {
                planOutput += `**Warnings:**\n`
                for (const w of simResult.warnings) {
                  planOutput += `- ⚠️ ${w}\n`
                }
              }
            }
          } catch (e) { log.warn("Silent catch: Non-fatal — simulation is advisory", { error: String(e) }) }
        }

        return {
          output: planOutput,
          metadata: { plan },
        }
      },
  }
}
